# -*- coding: utf-8 -*-
"""YoloV8_HPT_only_person.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qM1QcMiqyooS-SXDudv2yMP6X-ayHoaK

##Installing Ultralytics
"""

! pip install ultralytics

"""##Mounting Google Drive to put the outputs in a specific folder"""

from google.colab import drive
drive.mount('/content/drive')

"""### Use of Custom Dataset in google drive"""

# set the data yaml file path
data_yaml = "/content/drive/MyDrive/1:1_Agustya_Sinha/Agustya_nightvision_person-2/data.yaml"

"""### Hyper-Parameter Tuning

- Change the number of epochs and lrf (final learning rate) to tune and test the parameters.
"""

#Hyper parameters
epochs = 50
lr = 0.0001

# Train the model
! yolo task=detect mode=train model=yolov8s.pt data={data_yaml} optimizer="Adam" epochs={epochs} imgsz=640 lr0={lr} name=yolov8n_custom

# Evaluate the model
#! yolo task=detect mode=val model=/content/runs/detect/yolov8n_custom/weights/best.pt data={data_yaml}

"""### Move the model and results to google drive"""

import shutil
import os

def create_directory(directory_path):
    # Check if the directory exists
    if not os.path.exists(directory_path):
        # If it doesn't exist, create it
        os.makedirs(directory_path)
        print(f"Directory '{directory_path}' created.")
    else:
        print(f"Directory '{directory_path}' already exists.")

# Specify the directory path you want to check/create

model_name = 'yolov8_epochs_'+ str(epochs)+ '_lr_'+str(lr)
model_folder = '/content/drive/MyDrive/1:1_Agustya_Sinha/Models/Only person/'
destination_path = model_folder + model_name

# Call the function to check and create the directory
create_directory(destination_path)

source_path = '/content/runs/detect/yolov8n_custom'
shutil.move(source_path, destination_path)